version: "3.8"

services:
  app:
    container_name: store-app-server-synapsis
    image: 2be71fcdd15e
    build:
      context: .
      target: build
    volumes:
      - .:/app
    ports:
      - 7000:7000
